### ISSUE TITLE
Use *thiserror* for error handling

### ISSUE THREAD

**Issue by TianyiShi2001** [nonnominandus/rust-pdb#21]
I suggest using [**thiserror**](https://docs.rs/thiserror/1.0.23/thiserror/) for error handling. There's a great article explaining why it's more ergonomic and efficient than manual implementation (which convinced me to use **thiserror** in my crates): https://nick.groenen.me/posts/rust-error-handling/

[**rust-bio**](https://github.com/rust-bio/rust-bio/pull/400) have also adopted **thiserror** recently.

**Comment by nonnominandus** [comment]
Cool I will look into it as well then.

**Comment by nonnominandus** [comment]
I looked at it and did not really see obvious improvements over doing it manually, especially because I had a somewhat weird idea in my head of having an Error type which both can be used as a library return error (so easy for other programmers) as for display to end users.
